/**
 * Bot-vs-bot soak.
 *
 * The acceptance bar for the AI (CLAUDE.md architecture rule #1): a full four-turning-point
 * game, driven only by `Intent`s, must finish with **zero rejected intents**, no exception and
 * `phase === 'battleEnd'`. Random and greedy drivers visit states a purposeful agent never
 * would; the real AI is soaked as well so its own candidate generation is covered.
 *
 * Default run: synthetic killzones (open, corridor, Close Quarters) plus a sample of the real
 * extracted maps in `data/maps/**` when they exist. `KT_SOAK=full` widens it to every
 * synthetic map × every agent pairing × more seeds.
 */
import { describe, expect, it } from 'vitest';
import { TacticalAgent } from '../../src/ai/agent.ts';
import { GreedyAgent, RandomLegalAgent } from '../../src/ai/baseline.ts';
import { playGame, type GameResult } from '../../src/ai/runner.ts';
import type { Agent } from '../../src/ai/types.ts';
import type { KillzoneMap } from '../../src/core/types.ts';
import {
  AI_ROSTER,
  AI_ROSTER_BIG,
  aiContext,
  CRIT_OP_ID,
  closeQuartersMap,
  realMaps,
  syntheticMaps,
  TAC_OP_P1,
  TAC_OP_P2,
} from './fixtures.ts';

const FULL = process.env['KT_SOAK'] === 'full';

const agents: Record<string, () => Agent> = {
  random: () => new RandomLegalAgent(),
  greedy: () => new GreedyAgent(),
  tactical: () => new TacticalAgent({ difficulty: 'veteran' }),
};

function soakGame(map: KillzoneMap, seed: number, a: string, b: string, big = false): GameResult {
  const ctx = aiContext(seed);
  const roster = big ? AI_ROSTER_BIG : AI_ROSTER;
  return playGame({
    ctx,
    map,
    seed,
    critOpId: CRIT_OP_ID,
    rosters: { p1: { ...roster, tacOpId: TAC_OP_P1 }, p2: { ...roster, tacOpId: TAC_OP_P2 } },
    agents: { p1: agents[a]!(), p2: agents[b]!() },
  });
}

function expectClean(result: GameResult, label: string): void {
  const reasons = result.rejected.map((r) => `${JSON.stringify(r.intent).slice(0, 120)} → ${r.reason}`);
  expect(reasons, `${label}: rejected intents`).toEqual([]);
  expect(result.error, `${label}: runner error`).toBeUndefined();
  expect(result.state.phase, `${label}: final phase`).toBe('battleEnd');
  expect(result.turningPoints, `${label}: turning points played`).toBe(4);
  expect(['p1', 'p2', 'draw'], `${label}: winner`).toContain(result.winner);
}

describe('bot-vs-bot soak', () => {
  const pairings: [string, string][] = FULL
    ? [
        ['random', 'random'],
        ['greedy', 'greedy'],
        ['tactical', 'greedy'],
        ['tactical', 'random'],
        ['tactical', 'tactical'],
        ['random', 'tactical'],
      ]
    : [
        ['random', 'random'],
        ['greedy', 'greedy'],
        ['tactical', 'greedy'],
      ];

  it('plays full games on synthetic killzones with zero rejected intents', () => {
    const maps = syntheticMaps();
    const seeds = FULL ? [1, 2, 3, 4] : [1, 2];
    const played: string[] = [];
    for (const map of maps) {
      for (const [a, b] of pairings) {
        for (const seed of seeds) {
          const result = soakGame(map, seed, a, b);
          expectClean(result, `${map.id} ${a}-vs-${b} seed ${seed}`);
          played.push(`${map.id}/${a}v${b}/${seed}`);
        }
      }
    }
    // eslint-disable-next-line no-console
    console.log(`soak: ${played.length} synthetic games — maps ${maps.map((m) => m.id).join(', ')}`);
    expect(played.length).toBeGreaterThan(0);
  });

  it('exercises Close Quarters: Guard, On Guard interrupts and Condensed Environment', () => {
    const map = closeQuartersMap();
    expect(map.closeQuarters).toBe(true);
    const result = soakGame(map, 11, 'tactical', 'greedy', true);
    expectClean(result, 'close quarters');
    // The Guard action only exists on a Close Quarters map; the soak should have had the
    // chance to use it (it is not required to — the AI may judge it a waste of an AP).
    expect(result.intents).toBeGreaterThan(50);
  });

  it('plays full games on the real extracted maps, or reports that there are none yet', () => {
    const maps = realMaps(FULL ? 6 : 3);
    if (maps.length === 0) {
      // data/maps/** is generated by the map-extraction pipeline; it may not exist yet.
      // eslint-disable-next-line no-console
      console.log('soak: data/maps/** is empty — real-map soak skipped');
      expect(maps).toEqual([]);
      return;
    }
    for (const map of maps) {
      const result = soakGame(map, 5, 'greedy', 'greedy');
      expectClean(result, `real map ${map.id}`);
    }
    // eslint-disable-next-line no-console
    console.log(`soak: ${maps.length} real maps — ${maps.map((m) => m.id).join(', ')}`);
  });

  it('never leaks a cache between two different battles played back to back', () => {
    // Module-level caches are keyed by ids that repeat across games (`p1-0`, datacard ids,
    // map ids, board positions). A stale entry made an earlier soak run 8000 intents without
    // terminating, so two DIFFERENT battles are played in one process and both must finish.
    const first = soakGame(syntheticMaps()[0]!, 21, 'tactical', 'greedy');
    expectClean(first, 'back-to-back: first battle');
    const second = soakGame(closeQuartersMap(), 21, 'greedy', 'tactical', true);
    expectClean(second, 'back-to-back: second battle (different map, roster and seating)');
    const third = soakGame(syntheticMaps()[1]!, 22, 'random', 'tactical');
    expectClean(third, 'back-to-back: third battle');
    expect(second.intents).toBeLessThan(2000);
  });
});
